spring:
  application:
    name: ${SPRING_APP_NAME:ms-jurisia-judicial}
  profiles:
    active: dev
  docker:
    compose:
      enabled: false
  # ==== FUENTES DE DATOS ====
  datasource:
    sybase:
      jdbc-url: jdbc:sybase:Tds:172.17.16.66:2811/sij11_001_02_01
      username: usercsjan
      password: usercsjan
      driver-class-name: com.sybase.jdbc4.jdbc.SybDriver
      hibernate:
        dialect: org.hibernate.dialect.SybaseDialect
    mysql:
      jdbc-url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/${DATABASE_NAME:JURISDB_JUDICIAL}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: ${DATABASE_USERNAME:root}
      password: ${DATABASE_PASSWORD:123456}
      driver-class-name: com.mysql.cj.jdbc.Driver
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # ==== REDIS ====
  data:
    redis:
      host: localhost
      port: 6379
      prefix: jurisia_judicial
      ttl: 3600

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094,localhost:9095,localhost:9096}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 5
      compression-type: gzip

server:
  port: 8012

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

# ==== DOCUMENTACIÓN SWAGGER ====
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ==== RUTAS DE OTROS MICROSERVICIOS ====
api:
  consultaia:
    url: http://localhost:8011
    post:
      process:
        path: /v1/chatgpt/documento
  security:
    url: http://localhost:8010
    get:
      session:
        path: /v1/auth/session/:sessionId